### ISSUE TITLE
Implement primitive-based QuantumKernel

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#455]
### What should we add?

In this epic we plan to implement a new version of `QuantumKernel` that will leverage the primitives introduced in Qiskit Terra:

- [x] Implement new `QuantumKernel`. #437
- [x] Update `QSVC/QSVR` and `PegasosQSVC`. #437
- [x] Write a new or update the existing tutorial. #488 
- [x] Deprecate the existing quantum kernel implementation. #482

**Comment by adekusar-drl** [comment]
Closing the epic as all tasks are done.
