### ISSUE TITLE
Improve performance of the QML algorithms

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#57]
For now identified tasks/issues:
- [x] Turn on/off data gradients in QNNs when required.
- [x] Compute `forward` pass only once and store the results. Re-use the results of `forward` in `backward`.
- [x] Review batch batches in `NeuralNetworkClassifier` and `NeuralNetworkRegressor`

**Comment by adekusar-drl** [comment]
Things to do:
- Issue #59 (Make use of AerPauliExpectation for gradients, quantum Fisher information) to be completed in the next release.
- Profiling and performance tuning to be defined separately.
